export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const LOGOUT = "LOGOUT";

// PROJECTS
export const PROJECTS_LOADED_SUCCESS = "PROJECTS_LOADED_SUCCESS";
export const PROJECTS_LOADED_FAIL = "PROJECTS_LOADED_FAIL";
export const PROJECT_CREATED_SUCCESS = "PROJECT_CREATED_SUCCESS";
export const PROJECT_CREATED_FAIL = "PROJECT_CREATED_FAIL";
export const PROJECT_UPDATED_SUCCESS = "PROJECT_UPDATED_SUCCESS";
export const PROJECT_UPDATED_FAIL = "PROJECT_UPDATED_FAIL";
export const PROJECT_DELETED_SUCCESS = "PROJECT_DELETED_SUCCESS";
export const PROJECT_DELETED_FAIL = "PROJECT_DELETED_FAIL";